"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IMAGE_FILENAME_REGEX = exports.CURSOR_PATH = exports.BUCKET = exports.LATEST_WALLPAPERS_COUNT = exports.ARCHIVE_DIR = exports.WALLPAPERS_DIR = exports.ALL_WALLPAPERS_PATH = exports.README_MARK = exports.README_PATH = void 0;
exports.README_PATH = "./README.md";
exports.README_MARK = "# Latest wallpapers";
exports.ALL_WALLPAPERS_PATH = "./wallpaper/all.txt";
exports.WALLPAPERS_DIR = "./wallpaper";
exports.ARCHIVE_DIR = "./archive";
exports.LATEST_WALLPAPERS_COUNT = 10;
exports.BUCKET = "bing-wallpaper";
exports.CURSOR_PATH = "cursor.txt";
exports.IMAGE_FILENAME_REGEX = /\.(jpe?g|png|gif|bmp|webp|svg|avif|heic|heif)$/i;
