name: Check images

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Install ImageMagick and wrangler
      run: |
        sudo apt install imagemagick
        npm i -g wrangler

    - name: Install deps
      uses: denoland/setup-deno@v1

    - name: Check cloudflare R2 validate
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        rm -rf tmp
        mkdir tmp
        deno run --allow-all ./scripts/checkImages/checkImages.ts

    - name: Show corrupt images
      run: |
        ls tmp/*
